import Link from "next/link";
import { and, count, desc, eq, sql } from "drizzle-orm";
import { db, schema } from "@/db";
import { requireAdmin } from "@/modules/auth/session";
import { newArticle } from "@/modules/blog/actions";
import { STATUS_LABELS } from "@/modules/blog/types";
import { normalizeSearch } from "@/modules/blog/content";
import { PageHeader, Card } from "@/components/molecules";
import { SubmitButton } from "@/components/atoms";

export default async function BlogAdmin({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  await requireAdmin(); const params = await searchParams;
  const page = Math.max(1, Math.min(10000, Number(params.page) || 1)), q = normalizeSearch(params.q ?? "").slice(0, 100);
  const a = schema.articles;
  const where = and(params.status && STATUS_LABELS[params.status] ? eq(a.status, params.status) : undefined, params.category ? sql`${a.draft}->>'categoryId' = ${params.category}` : undefined, q ? sql`translate(lower(${a.draft}::text), 'يك', 'یک') like ${`%${q.replace(/[%_\\]/g, (v) => `\\${v}`)}%`}` : undefined, /^\d{4}-\d{2}-\d{2}$/.test(params.date ?? "") ? sql`(${a.publishedAt} at time zone 'Asia/Tehran')::date::text = ${params.date}` : undefined);
  const [rows, categories, totals, hearts] = await Promise.all([db.select().from(a).where(where).orderBy(desc(a.updatedAt), desc(a.id)).limit(30).offset((page - 1) * 30), db.select().from(schema.blogCategories), db.select({ total: count() }).from(a).where(where), db.select({ healthy: sql<boolean>`(${schema.workerHeartbeats.health}->>'blogSchedulerAt')::timestamptz > now() - interval '2 minutes'` }).from(schema.workerHeartbeats).orderBy(desc(schema.workerHeartbeats.seenAt)).limit(1)]);
  return <><PageHeader title="مقاله‌های بلاگ" /><form action={newArticle}><SubmitButton>مقاله جدید</SubmitButton></form>{(!hearts[0] || !hearts[0].healthy) && <p role="status" className="rounded-md bg-warning-bg p-4 text-warning">علامت حیات تازه‌ای از worker دریافت نشده؛ انتشار زمان‌بندی‌شده نیازمند worker فعال است.</p>}
    <Card><form className="mb-6 grid gap-3 sm:grid-cols-4"><input className="field" name="q" aria-label="جست‌وجوی مقاله" placeholder="جست‌وجوی عنوان و متن" defaultValue={params.q} /><select className="field" name="status" aria-label="وضعیت" defaultValue={params.status}><option value="">همه وضعیت‌ها</option>{Object.entries(STATUS_LABELS).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select><select className="field" name="category" aria-label="دسته" defaultValue={params.category}><option value="">همه دسته‌ها</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.title}</option>)}</select><label className="text-xs">تاریخ انتشار (میلادی/تهران)<input className="field" type="date" name="date" defaultValue={params.date} /></label><button className="btn btn-secondary h-11">جست‌وجو</button></form>
      <div className="overflow-x-auto"><table className="w-full text-right text-sm"><thead><tr>{["عنوان", "دسته", "نویسنده", "وضعیت", "انتشار / ویرایش", "عملیات"].map((h) => <th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r) => <tr className="border-t border-line" key={r.id}><td className="p-3">{r.draft.title || "بدون عنوان"}</td><td className="p-3">{categories.find((c) => c.id === r.draft.categoryId)?.title || "—"}</td><td className="p-3">سئو دیلی</td><td className="p-3">{STATUS_LABELS[r.status]}{r.scheduledFor && " · زمان‌بندی فعال"}{r.scheduleError && <p className="text-error">{r.scheduleError}</p>}</td><td className="p-3">{r.publishedAt?.toLocaleDateString("fa-IR", { timeZone: "Asia/Tehran" }) || "—"}<br />{r.updatedAt.toLocaleDateString("fa-IR", { timeZone: "Asia/Tehran" })}</td><td className="p-3"><Link className="text-brand underline" href={`/admin/blog/${r.id}`}>ویرایش / مدیریت</Link> · <Link href={`/admin/blog/${r.id}/preview`}>پیش‌نمایش</Link></td></tr>)}</tbody></table></div>{!rows.length && <p className="py-6 text-muted">هنوز مقاله‌ای با این شرایط وجود ندارد. محتوای واقعی را از «مقاله جدید» وارد کنید.</p>}
      <nav className="mt-4 flex gap-4" aria-label="صفحه‌بندی مقاله‌های مدیریت">{page > 1 && <Link href={`?${new URLSearchParams({ ...Object.fromEntries(Object.entries(params).filter(([, v]) => v !== undefined)) as Record<string, string>, page: String(page - 1) })}`}>صفحه قبل</Link>}{page * 30 < totals[0].total && <Link href={`?${new URLSearchParams({ ...Object.fromEntries(Object.entries(params).filter(([, v]) => v !== undefined)) as Record<string, string>, page: String(page + 1) })}`}>صفحه بعد</Link>}</nav>
    </Card></>;
}
